import mongoose from 'mongoose';

const AddressSchema = new mongoose.Schema({
  city: { type: String, default: 'Bogota' },
  country: { type: String, default: 'Colombia' },
  zipCode: { type: String },
  address: { type: String, required: true }
}, { _id: false });

const PhoneSchema = new mongoose.Schema({
  codeNumber: { type: String, default: '+57' },
  phoneNumber: { type: Number }
}, { _id: false });

const UserSchema = new mongoose.Schema({
  // userId will be generated by application logic (auto-increment sequence)
  userId: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  email: { type: String, required: true },
  address: { type: AddressSchema },
  phone: { type: PhoneSchema },
  suspended: { type: Boolean, default: false },
  deleted: { type: Boolean, default: false }
}, { timestamps: true });

export default mongoose.model('User', UserSchema);
